### ISSUE TITLE
Browser cookie 3 getting an error when trying to install.

### ISSUE THREAD

**Issue by Paxxous** [borisbabic/browser_cookie3#100]
I'm using python 3.10, and when I try and install browser cookie 3 with pip, it all seems fine until I get this:

`ERROR: Command errored out with exit status 1:
     command: 'C:\Users\blAnk\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\blAnk\\AppData\\Local\\Temp\\pip-install-my3pcpxi\\lz4_028ad1e7431e43e88b8e859b6ff37d72\\setup.py'"'"'; __file__='"'"'C:\\Users\\blAnk\\AppData\\Local\\Temp\\pip-install-my3pcpxi\\lz4_028ad1e7431e43e88b8e859b6ff37d72\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\blAnk\AppData\Local\Temp\pip-record-x581102y\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\blAnk\AppData\Local\Programs\Python\Python310\Include\lz4'
         cwd: C:\Users\blAnk\AppData\Local\Temp\pip-install-my3pcpxi\lz4_028ad1e7431e43e88b8e859b6ff37d72\
    Complete output (22 lines):
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.10
    creating build\lib.win-amd64-3.10\lz4
    copying lz4\version.py -> build\lib.win-amd64-3.10\lz4
    copying lz4\__init__.py -> build\lib.win-amd64-3.10\lz4
    creating build\lib.win-amd64-3.10\lz4\block
    copying lz4\block\__init__.py -> build\lib.win-amd64-3.10\lz4\block
    creating build\lib.win-amd64-3.10\lz4\frame
    copying lz4\frame\__init__.py -> build\lib.win-amd64-3.10\lz4\frame
    creating build\lib.win-amd64-3.10\lz4\stream
    copying lz4\stream\__init__.py -> build\lib.win-amd64-3.10\lz4\stream
    running build_ext
    building 'lz4._version' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\blAnk\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\blAnk\\AppData\\Local\\Temp\\pip-install-my3pcpxi\\lz4_028ad1e7431e43e88b8e859b6ff37d72\\setup.py'"'"'; __file__='"'"'C:\\Users\\blAnk\\AppData\\Local\\Temp\\pip-install-my3pcpxi\\lz4_028ad1e7431e43e88b8e859b6ff37d72\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\blAnk\AppData\Local\Temp\pip-record-x581102y\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\blAnk\AppData\Local\Programs\Python\Python310\Include\lz4' Check the logs for full command output.

C:\Users\blAnk>pip install browser_cookie3
Collecting browser_cookie3
  Using cached browser-cookie3-0.13.0.tar.gz (9.4 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pyaes in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from browser_cookie3) (1.6.1)
Requirement already satisfied: pbkdf2 in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from browser_cookie3) (1.3)
Collecting keyring
  Using cached keyring-23.2.1-py3-none-any.whl (33 kB)
Collecting lz4
  Using cached lz4-3.1.3.tar.gz (159 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pycryptodome in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from browser_cookie3) (3.11.0)
Requirement already satisfied: SecretStorage in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from browser_cookie3) (3.3.1)
Requirement already satisfied: importlib-metadata>=3.6 in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from keyring->browser_cookie3) (4.8.2)
Requirement already satisfied: pywin32-ctypes!=0.1.0,!=0.1.1 in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from keyring->browser_cookie3) (0.2.0)
Requirement already satisfied: cryptography>=2.0 in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from SecretStorage->browser_cookie3) (36.0.0)
Requirement already satisfied: jeepney>=0.6 in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from SecretStorage->browser_cookie3) (0.7.1)
Requirement already satisfied: cffi>=1.12 in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from cryptography>=2.0->SecretStorage->browser_cookie3) (1.15.0)
Requirement already satisfied: zipp>=0.5 in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from importlib-metadata>=3.6->keyring->browser_cookie3) (3.6.0)
Requirement already satisfied: pycparser in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from cffi>=1.12->cryptography>=2.0->SecretStorage->browser_cookie3) (2.21)
Using legacy 'setup.py install' for browser-cookie3, since package 'wheel' is not installed.
Using legacy 'setup.py install' for lz4, since package 'wheel' is not installed.
Installing collected packages: lz4, keyring, browser-cookie3
    Running setup.py install for lz4 ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\blAnk\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\blAnk\\AppData\\Local\\Temp\\pip-install-1piz8zy0\\lz4_38bde2108c034266a4f1f8ddbd186946\\setup.py'"'"'; __file__='"'"'C:\\Users\\blAnk\\AppData\\Local\\Temp\\pip-install-1piz8zy0\\lz4_38bde2108c034266a4f1f8ddbd186946\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\blAnk\AppData\Local\Temp\pip-record-5gd1r80y\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\blAnk\AppData\Local\Programs\Python\Python310\Include\lz4'
         cwd: C:\Users\blAnk\AppData\Local\Temp\pip-install-1piz8zy0\lz4_38bde2108c034266a4f1f8ddbd186946\
    Complete output (22 lines):
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.10
    creating build\lib.win-amd64-3.10\lz4
    copying lz4\version.py -> build\lib.win-amd64-3.10\lz4
    copying lz4\__init__.py -> build\lib.win-amd64-3.10\lz4
    creating build\lib.win-amd64-3.10\lz4\block
    copying lz4\block\__init__.py -> build\lib.win-amd64-3.10\lz4\block
    creating build\lib.win-amd64-3.10\lz4\frame
    copying lz4\frame\__init__.py -> build\lib.win-amd64-3.10\lz4\frame
    creating build\lib.win-amd64-3.10\lz4\stream
    copying lz4\stream\__init__.py -> build\lib.win-amd64-3.10\lz4\stream
    running build_ext
    building 'lz4._version' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\blAnk\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\blAnk\\AppData\\Local\\Temp\\pip-install-1piz8zy0\\lz4_38bde2108c034266a4f1f8ddbd186946\\setup.py'"'"'; __file__='"'"'C:\\Users\\blAnk\\AppData\\Local\\Temp\\pip-install-1piz8zy0\\lz4_38bde2108c034266a4f1f8ddbd186946\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\blAnk\AppData\Local\Temp\pip-record-5gd1r80y\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\blAnk\AppData\Local\Programs\Python\Python310\Include\lz4' Check the logs for full command output.

C:\Users\blAnk>pip install discord-webhook
Collecting discord-webhook
  Using cached discord_webhook-0.14.0-py3-none-any.whl (9.4 kB)
Requirement already satisfied: requests>=2.19.1 in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from discord-webhook) (2.26.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.19.1->discord-webhook) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.19.1->discord-webhook) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.19.1->discord-webhook) (1.26.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.19.1->discord-webhook) (3.3)
Installing collected packages: discord-webhook
Successfully installed discord-webhook-0.14.0

C:\Users\blAnk>pip install nuitka
Collecting nuitka
  Using cached Nuitka-0.6.17.7.tar.gz (3.2 MB)
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for nuitka, since package 'wheel' is not installed.
Installing collected packages: nuitka
    Running setup.py install for nuitka ... done
Successfully installed nuitka-0.6.17.7

C:\Users\blAnk>pip install browser-cookie3
Collecting browser-cookie3
  Using cached browser-cookie3-0.13.0.tar.gz (9.4 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pyaes in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from browser-cookie3) (1.6.1)
Requirement already satisfied: pbkdf2 in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from browser-cookie3) (1.3)
Collecting keyring
  Using cached keyring-23.2.1-py3-none-any.whl (33 kB)
Collecting lz4
  Using cached lz4-3.1.3.tar.gz (159 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pycryptodome in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from browser-cookie3) (3.11.0)
Requirement already satisfied: SecretStorage in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from browser-cookie3) (3.3.1)
Requirement already satisfied: importlib-metadata>=3.6 in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from keyring->browser-cookie3) (4.8.2)
Requirement already satisfied: pywin32-ctypes!=0.1.0,!=0.1.1 in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from keyring->browser-cookie3) (0.2.0)
Requirement already satisfied: cryptography>=2.0 in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from SecretStorage->browser-cookie3) (36.0.0)
Requirement already satisfied: jeepney>=0.6 in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from SecretStorage->browser-cookie3) (0.7.1)
Requirement already satisfied: cffi>=1.12 in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from cryptography>=2.0->SecretStorage->browser-cookie3) (1.15.0)
Requirement already satisfied: zipp>=0.5 in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from importlib-metadata>=3.6->keyring->browser-cookie3) (3.6.0)
Requirement already satisfied: pycparser in c:\users\blank\appdata\local\programs\python\python310\lib\site-packages (from cffi>=1.12->cryptography>=2.0->SecretStorage->browser-cookie3) (2.21)
Using legacy 'setup.py install' for browser-cookie3, since package 'wheel' is not installed.
Using legacy 'setup.py install' for lz4, since package 'wheel' is not installed.
Installing collected packages: lz4, keyring, browser-cookie3
    Running setup.py install for lz4 ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\blAnk\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\blAnk\\AppData\\Local\\Temp\\pip-install-ppv0fp36\\lz4_9212b24a4f1c46b38c2fe6726736e354\\setup.py'"'"'; __file__='"'"'C:\\Users\\blAnk\\AppData\\Local\\Temp\\pip-install-ppv0fp36\\lz4_9212b24a4f1c46b38c2fe6726736e354\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\blAnk\AppData\Local\Temp\pip-record-am4as3w6\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\blAnk\AppData\Local\Programs\Python\Python310\Include\lz4'
         cwd: C:\Users\blAnk\AppData\Local\Temp\pip-install-ppv0fp36\lz4_9212b24a4f1c46b38c2fe6726736e354\
    Complete output (22 lines):
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.10
    creating build\lib.win-amd64-3.10\lz4
    copying lz4\version.py -> build\lib.win-amd64-3.10\lz4
    copying lz4\__init__.py -> build\lib.win-amd64-3.10\lz4
    creating build\lib.win-amd64-3.10\lz4\block
    copying lz4\block\__init__.py -> build\lib.win-amd64-3.10\lz4\block
    creating build\lib.win-amd64-3.10\lz4\frame
    copying lz4\frame\__init__.py -> build\lib.win-amd64-3.10\lz4\frame
    creating build\lib.win-amd64-3.10\lz4\stream
    copying lz4\stream\__init__.py -> build\lib.win-amd64-3.10\lz4\stream
    running build_ext
    building 'lz4._version' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\blAnk\AppData\Local\Programs\Python\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\blAnk\\AppData\\Local\\Temp\\pip-install-ppv0fp36\\lz4_9212b24a4f1c46b38c2fe6726736e354\\setup.py'"'"'; __file__='"'"'C:\\Users\\blAnk\\AppData\\Local\\Temp\\pip-install-ppv0fp36\\lz4_9212b24a4f1c46b38c2fe6726736e354\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\blAnk\AppData\Local\Temp\pip-record-am4as3w6\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\blAnk\AppData\Local\Programs\Python\Python310\Include\lz4' Check the logs for full command output.`

**Comment by Paxxous** [comment]
I just found out that I just had to install an older version of python

**Comment by wkingnet** [comment]
> 我刚刚发现我只需要安装旧版本的python
same error.

This version is for the python3 version, but I can’t install it from python 3.1 to 3.10.

**Comment by Paxxous** [comment]
> > 我刚刚发现我只需要安装旧版本的python
> 
> same error. This version is for the python3 version, but I can’t install it from python 3.1 to 3.10.

I found the fix, I just installed python 3.9.8, and it seemed to work then.

**Comment by wkingnet** [comment]
> 

thank you! I will try it
