### ISSUE TITLE
browser_cookie3.BrowserCookieError: Failed to find Chrome cookie

### ISSUE THREAD

**Issue by cbellew** [borisbabic/browser_cookie3#106]
Hi,

Our code has been working fine for some time but recently we got a "browser_cookie3.BrowserCookieError: Failed to find Chrome cookie" error.

We have updated browser_cookie3 to the latest 0.13.0 but it has not resolved this issue. Can anyone help please?

**Comment by Elkosscom** [comment]
The issue lies with Chrome version 96 or above. This version moved the cookie file from profile_dir/Cookies, to profile_dir/Network/Cookies.
You will either have to downgrade chrome to version below 96, or point to the cookie file directly.

**Comment by XP1** [comment]
I created a symlink on Windows. Working as a tempfix until Chrome restarts and deletes it.

```
cd "%LocalAppData%\Google\Chrome\User Data\Default"
mklink "Cookies" "Network\Cookies"
```

**Comment by githublyff** [comment]
Use the system system environment variable splicing path Os.Getenv and Join:
```
import os
print(os.path.join(os.getenv('LOCALAPPDATA', '') + r'\Google\Chrome\User Data\Default\Network\Cookies'))
```

Running well!

**Comment by Falydoor** [comment]
After updating Chrome on Mac OS X, I had to manually set `cookie_file` to:

```python
# "Default" is replaced by "Profile 1"
cookie_file = f"{os.getenv('HOME')}/Library/Application Support/Google/Chrome/Profile 1/Cookies"
```

**Comment by frostming** [comment]
This issue still exists, the cookies are stored at `$HOME/Library/Application Support/Google/Chrome/Profile {n}/Cookies`, interestingly, browsercookie@master can load them correctly.

**Comment by rafiibrahim8** [comment]
Hi @frostming, 
I'm currently looking at the issue. Please give me some time to figure out how to implement it properly and efficiently without breaking existing setups. 
Thank you
