### ISSUE TITLE
Firefox cookies.sqlite location change for snap

### ISSUE THREAD

**Issue by headkaze** [borisbabic/browser_cookie3#108]
Ubuntu 21.10 makes Firefox snap installation the default which means its user directory has changed from `~/.mozilla/firefox` to `~/snap/firefox/common/.mozilla/firefox`

**Comment by headkaze** [comment]
Created a [pull request](https://github.com/borisbabic/browser_cookie3/pull/109)

**Comment by rafiibrahim8** [comment]
fixed in #134
