### ISSUE TITLE
Functionality for Chrome incognito?

### ISSUE THREAD

**Issue by Andrew3019** [borisbabic/browser_cookie3#110]
Would it be possible to modify the source code so that this could grab cookies from a Chrome incognito session? I have tried finding the file path for incognito cookies but I cannot find it, and that seems to be the only obstacle for making this work. 
Perhaps someone knows where the file is located?

**Comment by 9ggy** [comment]
I'm pretty sure that incognito mode doesnt store cookies, therefore you cant grab them.

**Comment by rafiibrahim8** [comment]
Chrome doesn't save cookies in incognito mode.


See: https://support.google.com/chrome/answer/9845881?hl=en#zippy=%2Chow-incognito-mode-works

> In Incognito, none of your browsing history, [cookies](https://support.google.com/chrome/answer/95647) and site data, or information entered in forms are saved on your device. ...
