### ISSUE TITLE
ModuleNotFoundError: No module named 'browser_cookie3

### ISSUE THREAD

**Issue by splendex** [borisbabic/browser_cookie3#117]
I get this error even though I installed browser_cookie 3 trough cmd using:

`pip3 install browser-cookie3`

cmd:
`Using cached browser-cookie3-0.13.0.tar.gz (9.4 kB)
Requirement already satisfied:`

My code:
```
import browser_cookie3

class cookiePy:
	def __init__(self):
		pass
```

**Comment by kcinbk** [comment]
Hi @splendex, I'm running into the same problem. Did you figure out how to fix the error?
