### ISSUE TITLE
support for Firefox on Windows?

### ISSUE THREAD

**Issue by yhcharles** [borisbabic/browser_cookie3#12]
It seems the original package has support for Firefox on Windows already.
https://bitbucket.org/richardpenman/browsercookie
Is there any plan for that?

**Comment by borisbabic** [comment]
I do not have plans to add additional Windows support, however I wouldn't reject a pull request that adds it.

**Comment by borisbabic** [comment]
Closing this as old. If somebody want's to add this I'll accept a pull request.
