### ISSUE TITLE
browser_cookie3 cryptography error - Termux

### ISSUE THREAD

**Issue by 13Quavo** [borisbabic/browser_cookie3#127]
Hi,

I'm having an Issue with Cryptography.
It says ERROR.. Failed building wheel for cryptography

Any solution? Thank you

**Comment by 13Quavo** [comment]
https://pastebin.com/1WqCyRhz

**Comment by f1refa11** [comment]
Try executing this in Termux:
```
CARGO_BUILD_TARGET=aarch64-linux-android && pip install cryptography
```

**Comment by rafiibrahim8** [comment]
`browser_cookie3` doesn't support Termux. Sorry :(
