### ISSUE TITLE
Saving cookies in a file

### ISSUE THREAD

**Issue by Czerniii** [borisbabic/browser_cookie3#128]
As I want to use requests library within a cloud is it possible to save my browser cookies in a file and load it in a different environment?

Thanks!

**Comment by rafiibrahim8** [comment]
It is possible to save cookies to a file using the `requests`s `dict_from_cookiejar` and `cookiejar_from_dict` method.

#### To save the cookies:
```python
import json
import browser_cookie3
from requests.utils import dict_from_cookiejar

cookies = browser_cookie3.firefox()
cookies = dict_from_cookiejar(cookies)
with open('cookies.json','w') as f:
    json.dump(cookies,f , indent=4)
```

#### To load the cookies:
```python
import json
from requests.utils import cookiejar_from_dict

with open('cookies.json','r') as f:
    cookies = cookiejar_from_dict(json.load(f))
```
