### ISSUE TITLE
Use `browser_cookie3` in `aiohttp.ClientSession`

### ISSUE THREAD

**Issue by DvaMishkiLapa** [borisbabic/browser_cookie3#132]
I'm trying to pass cookies into an asynchronous session, but it's not working. I think I've gone through everything that comes to mind.
Is there a solution to this issue?

Code example:
```python
import asyncio

import aiohttp
import browser_cookie3
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
cookies = browser_cookie3.load(domain_name='.vk.com')

url = 'https://vk.com/doc186278615_429743293'


async def main():
    async with aiohttp.ClientSession(cookies=cookies) as session:
        async with session.get(url, timeout=5) as response:
            print(response.status)
            print(response.url)
            print(response.headers['content-type'])

asyncio.run(main())
```

1. Else`aiohttp.ClientSession(cookies=cookies)`, then
```python
TypeError: cannot unpack non-iterable Cookie object
```
2. Else `aiohttp.ClientSession(cookies=cookies._cookies)`, then:
I don't get an error, but I don't see the desired result. Cookies didn't work, the resource didn't give the desired result.

3. Else `aiohttp.ClientSession(cookies={"fluxSessionData": cookies._cookies['.login.vk.com']['/'].values})`, then:
Similar to point 2. This solution was taken from here: https://stackoverflow.com/questions/60329451/aiohttp-with-browser-cookie3

4. Else `aiohttp.ClientSession(cookies={'.login.vk.com': cookies._cookies['.login.vk.com']['/'].values})`, then:
Similar to point 2.

5. Else `aiohttp.ClientSession(cookies={'.login.vk.com': {'/': {cookies._cookies['.login.vk.com']['/'].values}}})`, then:
Similar to point 2.

I checked the solution through `requests`, everything works fine there. But I need an asynchronous approach.

**Comment by rafiibrahim8** [comment]
`aiohttp.ClientSession` needs cookies as `dict`. On the other hand `browser_cookie3` returns cookies as `CookieJar`. You need to convert `CookieJar` to `dict`.
```python
from requests.utils import dict_from_cookiejar
import browser_cookie3

cookies = dict_from_cookiejar(browser_cookie3.load(domain_name='.vk.com'))
```

**Comment by DvaMishkiLapa** [comment]
Man, that was obvious😄.
Thanks for the solution!
