### ISSUE TITLE
Safari - Can not find Safari cookie file

### ISSUE THREAD

**Issue by skoobasteeve** [borisbabic/browser_cookie3#135]
Safari support is currently not working for me on macOS Monterey 12.5. The module looks for cookies at `~/Library/Cookies/Cookies.binarycookies`, but my cookies seem to be stored as individual sqlite files under `~/Library/Safari/LocalStorage`. Not sure if it's possible to get the data you need from these files, but let me know if there's a good workaround.

Thank you!

**Comment by elvin-hwang** [comment]
Having the same issue here

**Comment by rafiibrahim8** [comment]
I couldn't work on it as I don't have a mac. Does anyone want to work on it? I will help along the way.

**Comment by shatyuka** [comment]
Moved to app's sandbox container.
`~/Library/Containers/com.apple.Safari/Data/Library/Cookies/Cookies.binarycookies`
