### ISSUE TITLE
Extract a specific cookie by its name.

### ISSUE THREAD

**Issue by victorfaria87** [borisbabic/browser_cookie3#139]
Hello,
browser_cookie3 has been working great so far.
but i get all the cookies from the domain i am extracting wne executing the code.
is it possible to extrat jut a specific cookie?

**Comment by rafiibrahim8** [comment]
@victorfaria87 you can use `dict_from_cookiejar` from `requests.utils` to convert cookies to `dict`. Then get the cookie by name. For example to get the cookie name `NID` from google.com:
```python
import browser_cookie3
from requests.utils import dict_from_cookiejar

cookies = browser_cookie3.chrome(domain_name="google.com")
cookies = dict_from_cookiejar(cookies)
print(cookies.get('NID'))
```
