### ISSUE TITLE
Chrome cookies table changed in version 66

### ISSUE THREAD

**Issue by josegabriel83** [borisbabic/browser_cookie3#14]
Chrome version 66 (in OSX) has changed the name of the "secure" column in the cookies table to "is_secure", so Chrome.load() fails with (sqlite3.OperationalError: no such column: secure). 

Culprit:
cur.execute('SELECT host_key, path, **secure**, expires_utc, name, value, encrypted_value '
                    'FROM cookies WHERE host_key like "%{}%";'.format(self.domain_name))

**Comment by borisbabic** [comment]
The same issue is present on linux as well, I'll fix this today/tomorrow.

**Comment by borisbabic** [comment]
0.6.4 is now available, sorry for the delay.

**Comment by phester66** [comment]
And on Windows
