### ISSUE TITLE
Having troubles running the library on VSC

### ISSUE THREAD

**Issue by kcinbk** [borisbabic/browser_cookie3#143]
Tried to import the library on Visual Studio Code but kept bouncing back  ModuleNotFoundError: No module named 'browser_cookie3' Any idea how to fix it?

**Comment by yes-0001** [comment]
just do this command in cmd:
pip install browser_cookie3

if that doesn't work and/or pip is not a command then try this:
py -m pip install browser_cookie3

if none of those fix your issue, then I have no clue what's wrong

**Comment by rafiibrahim8** [comment]
@kcinbk, 
It can happen when you are installing `browser_cookie3` in a different virtual environment than VS Code.
