### ISSUE TITLE
Support Opera

### ISSUE THREAD

**Issue by Tadaboody** [borisbabic/browser_cookie3#15]
Let `load` extract cookies from opera as well

**Comment by borisbabic** [comment]
AFAIK Opera is based on chromium so you should be able to just use it's cookies as though they were chrome cookies.

Could you please try the following:

```python
import browser_cookie3
import os
opera_cookie_file = os.path.expanduser('~/.config/opera/Cookies')  # change to the path to your opera cookies file
cj = browser_cookie3.chrome(cookie_file=opera_cookie_file)
# ... use the cookie jar.
```

**Comment by Tadaboody** [comment]
Currently running windows - where are the cookies stored there?

**Comment by rafiibrahim8** [comment]
This can be closed now.
