### ISSUE TITLE
Error when loading chrome cookies after chrome update

### ISSUE THREAD

**Issue by Bouby308** [borisbabic/browser_cookie3#150]
After I update to Chrome 109, this error occurs. This doesn't happen to Edge. May be the new Chrome update screw something up?

```
Traceback (most recent call last):

  File "C:\Users\default\anaconda3\envs\default\lib\site-packages\browser_cookie3\__init__.py", line 307, in load
    'FROM cookies WHERE host_key like ?;', ('%{}%'.format(self.domain_name),))

OperationalError: no such table: cookies
```

**Comment by rafiibrahim8** [comment]
@Bouby308 
I can't reproduce it on my machine.
Can you provide the following information:

1. OS name and version
2. Python version
3. Full chrome version

**Comment by Bouby308** [comment]
OS: Windows 10 22H2 19045.2364
Python Version: 3.7.4
Chrome version: 109.0.5414.75

**Comment by Bouby308** [comment]
After reinstalling browser-cookies3, the cookies are loaded without errors.
However, the loaded cookies are not latest.

**Comment by rafiibrahim8** [comment]
You may need to close the browser to get the latest cookies. Browsers usually don't save the cookies on the sqlite database until it has been closed.

**Comment by Bouby308** [comment]
Seems to solve the problem. Thanks.
