### ISSUE TITLE
browser_cookie3.opera() and browser_cookie3.load() does not detect Opera GX

### ISSUE THREAD

**Issue by yes-0001** [borisbabic/browser_cookie3#151]
I'm trying to get cookie data from Opera GX, I assumed opera would be both opera and Opera GX but sadly not, not even detected in the load function, I recently pip installed browser_cookie3 so it should be 100% updated

if you could add Opera GX support that would be great <3

**Comment by yes-0001** [comment]
here's more info, what happens is, it 100% detects the cookie is there in chrome, and it adds the cookie to a table, but then once it reaches opera gx, it 100% detects the cookie, but it doesn't add the cookie, there is no possible way to see what the cookie's info is or anything, they are both the same code but one is opera() and one is chromeium()

when I just try to do opera() by itself, it gives me a "browser_cookie3.BrowserCookieError: Failed to find Opera cookie" error

**Comment by yes-0001** [comment]
code:
`
def meower():
    data = []

        try:
            cookies = browser_cookie3.firefox(domain_name='')
            for cookie in cookies:
                if cookie.name == '':
                    # data.append(cookies)
                    data.append(cookie.value)
                    return data
        except:
            print("meow1")

        try:
            cookies = browser_cookie3.chromium(domain_name='')
            for cookie in cookies:
                if cookie.name == '':
                    # data.append(cookies)
                    data.append(cookie.value)
                    return data
        except:
            print("meow2")

        try:
            cookies = browser_cookie3.edge(domain_name='')
            for cookie in cookies:
                if cookie.name == '':
                    # data.append(cookies)
                    data.append(cookie.value)
                    return data
        except:
            print("meow3")

        try:
            cookies = browser_cookie3.opera(domain_name='')
            for cookie in cookies:
                if cookie.name == '':
                    # data.append(cookies)
                    data.append(cookie.value)
                    return data
        except:
            print("meow4")

        try:
            cookies = browser_cookie3.chrome(domain_name='')
            for cookie in cookies:
                if cookie.name == '':
                    # data.append(cookies)
                    data.append(cookie.value)
                    return data
        except:
            print("meow5")

cookies = meower()
print(cookies)

# for x in range(len(cookies)):
#     print(cookies[x])
`

**Comment by rafiibrahim8** [comment]
Hey @yes-0001,
I'm looking at it.

**Comment by yes-0001** [comment]
thanks <3

**Comment by rafiibrahim8** [comment]
Added in #152
