### ISSUE TITLE
browser_cookie3.firefox() fails in 0.19 due to incorrect json.load() use

### ISSUE THREAD

**Issue by kartiksubbarao** [borisbabic/browser_cookie3#188]
In 0.19, `browser_cookie3.firefox()` fails with the following error:

```
AttributeError: 'str' object has no attribute 'read'
```

This is due to this part of the eb885ff change:

![image](https://github.com/borisbabic/browser_cookie3/assets/134209/a4b5f689-eade-4cc3-8aec-06c5bacefb65)

json.load() does not take a filename as a parameter. A simple fix would be:

```
with open(self.session_file, 'rb') as file_obj:
    json_data = json.load(file_obj)
```

**Comment by kartiksubbarao** [comment]
Thanks @rafiibrahim8 !

**Comment by savek-cc** [comment]
@rafiibrahim8 
With chrome cookies unavailable due to the new encryption and firefox support still broken in the last release: Will there be an updates release including this fix any time soon? (Yes, local patching is possible of course)

**Comment by rafiibrahim8** [comment]
hi @savek-cc, I will be woking on it this weekend.
