### ISSUE TITLE
BrowserCookieError: Can not find cookie file at: url

### ISSUE THREAD

**Issue by mahesh3097** [borisbabic/browser_cookie3#19]
I get this error when I am trying to access cookies from a url

import browser_cookie3
cj=browser_cookie3.chrome(url)
with session() as c :
        request=c.get(some_url, cookies=cj)

Is there anything wrong ?
Is it an issue with the package or the chrome browser

**Comment by borisbabic** [comment]
The first argument to `browser_cookie3.chrome()` is the cookie file not the url.

**Comment by borisbabic** [comment]
I'm closing this since it looks like incorrect usage. If you have further errors please include the version of browser_cookie3 you are using.
