### ISSUE TITLE
Chrome v115 broke support

### ISSUE THREAD

**Issue by isorropisths** [borisbabic/browser_cookie3#192]
hey there

Chrome v115 (115.0.5790.170) broke support, v114 was the last version that it worked.

Log:

Traceback (most recent call last):
/browser_cookie3/__init__.py", line 494, in load
    cur.execute('SELECT host_key, path, secure, expires_utc, name, value, encrypted_value, is_httponly '
sqlite3.OperationalError: no such table: cookies

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
/browser_cookie3/__init__.py", line 1160, in chrome
    return Chrome(cookie_file, domain_name, key_file).load()
/browser_cookie3/__init__.py", line 498, in load
    cur.execute('SELECT host_key, path, is_secure, expires_utc, name, value, encrypted_value, is_httponly '
sqlite3.OperationalError: no such table: cookies

**Comment by abubelinha** [comment]
@isorropisths how did you solve it?
I get the same message under Chrome Version 109.0.5414.120 (Official Build) (64-bit)
