### ISSUE TITLE
 SNlM0e value not found. 

### ISSUE THREAD

**Issue by githubuser2007** [borisbabic/browser_cookie3#193]
while trying to use this library i get this error when i run my script

ERROR:  File "C:\Users\{User}\Desktop\code-playground\python-learning\bard\app.py", line 7,     print(Bard().get_answer(req)) 11\Lib\site-packages\bardapi\core.py", line 55, in __init__     self.SNlM0e = self._get_snim0e()                   ^^^^^^^^^^^^^^^^^^   File "C:\Users\{User}\AppData\Local\Programs\Python\Python311\Lib\site-packages\bardapi\core.py", line 128, in _get_snim0e     raise Exception( Exception: SNlM0e value not found. Double-check __Secure-1PSID value or pass it as token='xxxxx'.

SCRIPT:

from bardapi import Bard
import os

os.environ["_BARD_API_KEY"] = {placeholder for api key}

req = input("hwo shall i assist you today?: ")
print(Bard().get_answer(req))

**Comment by reee** [comment]
I got this issue too

**Comment by rafiibrahim8** [comment]
Hi, I think you have intended to create the issue in the Google Bard repo. :smile:
