### ISSUE TITLE
sqlite3.OperationalError: no such column: secure in Chome 73

### ISSUE THREAD

**Issue by sceptre01** [borisbabic/browser_cookie3#20]
'FROM cookies WHERE host_key like "%{}%";'.format(self.domain_name))
sqlite3.OperationalError: no such column: secure
Exception ignored in: <function Chrome.__del__ at 0x000001E601E170D0

In the init file at line 87. changing the secure to is_secure fixes the issues in many newer version of browsers.

Fix:
cur.execute('SELECT host_key, path, is_secure, expires_utc, name, value, encrypted_value '\
                'FROM cookies WHERE host_key like "%{}%";'.format(self.domain_name))

**Comment by borisbabic** [comment]
What version of `browser_cookie3` are you using?

**Comment by sceptre01** [comment]
Oh, I was installing from google it was showing cached version of 0.6.0, forget to check out the latest one.
