### ISSUE TITLE
How can automaticly get cookies value in no gui servers?

### ISSUE THREAD

**Issue by Usercodersystem** [borisbabic/browser_cookie3#203]
How can automaticly get cookies value in no gui servers?
i need use automatic get cookie values in no gui server like pythonanywhere.com

**Comment by OlegRuban-ai** [comment]
I'm also interested in this question. We need to receive cookies from the site, but requests are made on a remote server without gui

**Comment by Usercodersystem** [comment]
OK Thanks

**Comment by OlegRuban-ai** [comment]
> OK Thanks

Can you do this in the future? A very necessary feature for many.

**Comment by LuisBeOnline** [comment]
+1

**Comment by borisbabic** [comment]
Supper was added for text based browsers (lynx and w3m), you can use one of those.
