### ISSUE TITLE
Not Working On Windows OS

### ISSUE THREAD

**Issue by Usercodersystem** [borisbabic/browser_cookie3#204]
Hello I Have A permissionError after get cookie value From chrome.
![Uploading Screenshot_20240308_213039_Microsoft Remote Desktop.jpg…]()

**Comment by FeldrinH** [comment]
The screenshot link is broken, but this is probably a duplicate of https://github.com/borisbabic/browser_cookie3/issues/180

**Comment by Usercodersystem** [comment]
@FeldrinH oh this js github bug🤣🤣
