### ISSUE TITLE
I am unable to use the script with Firefox on Linux

### ISSUE THREAD

**Issue by kaya-arro** [borisbabic/browser_cookie3#213]
I'm running `Firefox 131.0.3` on Endeavour OS. I have used the `-b` and `-c` flags and double checked that I am pointing the script to the correct cookies file. I get the error,

    Retrieving album links from user [me]'s collection.
    ERROR: No div with pagedata found for user at url [https://bandcamp.com/me]
    WARN: No album links found for user [me]. Are you logged in and have you selected the correct browser to pull cookies from?

Thanks for your attention, and thanks so much for developing this very useful tool!

**Comment by borisbabic** [comment]
This output does not look like it's from browser_cookie
