### ISSUE TITLE
Does not work with chrome 73 and ubuntu

### ISSUE THREAD

**Issue by httpedo13** [borisbabic/browser_cookie3#22]
I modified this script (https://github.com/codergator/viner) with browser cookie 3 but can't login with chrome 73 and ubuntu. While with macos and chrome 73 it works.

**Comment by borisbabic** [comment]
What version are you using? Are the appropriate cookies found? Are you sure you're logged in and that the cookie file used is the default one (if you've changed in browser users then it's probably not)?

**Comment by httpedo13** [comment]
I modified the script using BROWSERCOOKIE3, it doesn't even work with original Cookie browser. Yes, I logged in

**Comment by borisbabic** [comment]
What version of browsercookie3 are you using? Are there only issues when you run it in that script or when you run browsercookie3 outside the script?

**Comment by httpedo13** [comment]
I install browsercookie3 yesterday with pip3, so i use the latest version. I don't run browsercookie outside the script but i run with macos and Google chrome and i don't have any problem

**Comment by httpedo13** [comment]
https://bitbucket.org/richardpenman/browsercookie/issues/29/silent-decryption-failure-in-newer-chrome

**Comment by borisbabic** [comment]
I need more info to be able to help. I do not have issues on linux (not ubuntu) with chrome 73. I will help you with browsercookie3 issues, but this repo is not for me to help you get some script running. Please confirm that browsercookie3 does not work correctly, not that the script doesn't work. Please be certain that you are using the correct cookie file.

**Comment by httpedo13** [comment]
`import browser_cookie3
import requests

url=https://www.amazon.it/gp/vine
cj=browser_cookie3.chrome()
r=requests.get(url,cookies=cj)
print(r.text)`


I tried to copy the example in this script. I logged into chrome 73 on ubuntu and the "print" returns the login page, it doesn't enter.

**Comment by borisbabic** [comment]
What DE are you using? Try running chrome with `--password-store=basic` then sign out/sign in and see if that helps.

**Comment by httpedo13** [comment]
nothing..

**Comment by borisbabic** [comment]
Can you follow https://github.com/borisbabic/browser_cookie3#fresh-cookie-files using `--password-store=basic` and see if there is anything in the cookie jar? Also could you upload the new cookie file so I can check? I'll try and get you a cookie file to test later when I have the time.
