### ISSUE TITLE
Does not work Chrome Version 75.0.3770.142

### ISSUE THREAD

**Issue by linusgvr** [borisbabic/browser_cookie3#26]
Does not work Chrome Version 75.0.3770.142

**Comment by borisbabic** [comment]
Can you give more details? What are you trying and what happens?

**Comment by linusgvr** [comment]
Below is my code:

Cookiejar = browser_cookie3.chrome(domain_name='knoema.com')
requests.get(API_URL, cookies=Cookiejar).content

But this does not work, If I open "API_URL" in chrome browser then I get required Data

**Comment by linusgvr** [comment]
> Can you give more details? What are you trying and what happens?

Below is my code:

Cookiejar = browser_cookie3.chrome(domain_name='knoema.com')
requests.get(API_URL, cookies=Cookiejar).content

But this does not work, If I open "API_URL" in chrome browser then I get required Data where I have logged in to knoema.com.

**Comment by borisbabic** [comment]
What do you mean by does not work? What happens? 

What OS are you using? If you're using linux try running chrome with `--password-store=basic` then sign out/sign in.

**Comment by borisbabic** [comment]
Closing due to lack of information.
