### ISSUE TITLE
'Failed to find Firefox cookie' in firefox 68

### ISSUE THREAD

**Issue by anasofiapaixao** [borisbabic/browser_cookie3#33]
browser-cookie3 fails to find the cookie store in Firefox 68.3.0esr 32-bit, running on Windows 10 Enterprise 64-bit. In that system, the cookie store is actually located under C:\Users\<username>\AppData\Roaming\Mozilla\Firefox\Profiles\<username> which is not being checked by the library.

**Comment by borisbabic** [comment]
Could you please provide the content of the `profiles.ini` file (you might need to remove usernames)? It should be located in the `Firefox` folder.

**Comment by anasofiapaixao** [comment]
I've asked the person for the file, this it what it has:

```
[InstallE7CF176E110C211B]
Default=Profiles/USERNAME

[Profile0]
Name=default
IsRelative=1
Default=1
Path=Profiles/USERNAME

[General]
StartWithLastProfile=1
Version=2
```

I've actually started working on a PR for it, as that is the client's system where I need my project to run :)

**Comment by borisbabic** [comment]
I was to add support today on for checking the `profiles.ini`  if it's not found elsewhere, in case that's what your PR is going to do.

When I release 1.0 I will probably make this the first thing checked for firefox.

**Comment by borisbabic** [comment]
0.9.0 has been released with support for checking the `profiles.ini`

**Comment by anasofiapaixao** [comment]
Hah, yes it was! I only checked github now and had it already done. I did a bit of cleanup on the way that might still make a useful PR once i merge this back to my fork and fix the conflicts, though:
https://github.com/anasofiapaixao/browser_cookie3/commit/a271014866bcce9bd37d0c6a2662f7b58c42aa5d

**Comment by anasofiapaixao** [comment]
Oh, and since I've been on this, I've noticed that configparser was added as a dependency, but at least in my testing it doesn't seem to be necessary for the parsing to be done correctly, which makes sense with [PyPI's description of it](https://pypi.org/project/configparser/): it's just a backport of python3's configparser for use with earlier versions of python, and the overhaul it got in 3.2 doesn't appear to conflict with anything being used in browser-cookie.

**Comment by anasofiapaixao** [comment]
all done in PR #41
