### ISSUE TITLE
Issue Getting Chrome Cookies - Windows 7, Chrome 79.0.3945.117

### ISSUE THREAD

**Issue by brooksmcmillin** [borisbabic/browser_cookie3#39]
Here is the error I'm getting trying to import Chrome cookies. test.py is 2 lines

`import browser_cookie3
cookies = browser_cookie3.chrome()`

Here is the error I get. It was working before, though I haven't run the script using this call in a while so I'm not sure exactly when it broke. 

> 
> Traceback (most recent call last):
>   File "test.py", line 3, in <module>
>     cookies = browser_cookie3.chrome()
> File "venv\lib\site-packages\browser_cookie3\__init__.py", line 351, in chrome
>     return Chrome(cookie_file, domain_name).load()
>   File "venv\lib\site-packages\browser_cookie3\__init__.py", line 180, in load
>     expires = expires.timestamp()
> OSError: [Errno 22] Invalid argument
> Exception ignored in: <function Chrome.__del__ at 0x00000000035DBD90>
> Traceback (most recent call last):
>   File "venv\lib\site-packages\browser_cookie3\__init__.py", line 150, in __del__
>     os.remove(self.tmp_cookie_file)
> PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '~\\AppData\\Local\\Temp\\tmprvc6vp3c.sqlite'

browser_cookie3.firefox() still seems to work as expected.

**Comment by brooksmcmillin** [comment]
![image](https://user-images.githubusercontent.com/16271714/72627421-199aee80-3912-11ea-9896-bc4e2e6de2fd.png)



It looks like it might be an issue with a specific cookie I'm getting. When I clear all my Chrome cookies the error disappears, but when I log into the site I need some cookies from, one looks to have a date with year 9998 that might be causing the error.

**Comment by brooksmcmillin** [comment]
![image](https://user-images.githubusercontent.com/16271714/72628170-6632f980-3913-11ea-9a77-f2151baa4ae5.png)

Pretty much confirmed it's an issue with the datetime.datetime.timestamp() function.

**Comment by brooksmcmillin** [comment]
Found the maximum supported timestamp in the datetime package to be 32536799999

https://stackoverflow.com/questions/46133223/maximum-value-of-timestamp/47291926
![image](https://user-images.githubusercontent.com/16271714/72629287-a4311d00-3915-11ea-8e4f-a28e1deef22e.png)

For my system I just changed the offset line to `offset = min(int(item[3]), 32536799999000000)` and everything is working again. Not sure how prevalent this issue is across other operating systems, but I have a few I can test with this weekend to see if I can come up with a fix that doesn't constrain systems that can handle larger timestamps.

**Comment by borisbabic** [comment]
Could you confirm whether `datetime.datetime(2038, 1, 21).timestamp()` and `datetime.datetime(2038, 1, 17).timestamp()` cause errors ? I think it could be that the error happens due to the [year 2038 problem](https://www.wikiwand.com/en/Year_2038_problem).

**Comment by brooksmcmillin** [comment]
![image](https://user-images.githubusercontent.com/16271714/72814946-89b7b600-3c2b-11ea-8e87-21a19684d8fe.png)

Those actually all work, tried `datetime.datetime(2038, 12, 31).timestamp()` as well just for good measure. For some reason datetime has the other limit instead.

**Comment by netchose** [comment]
same pb after upgrading from chrome79 to 80.
Python version 3.8 /windows 10 64bit

**Comment by brooksmcmillin** [comment]
@netchose I believe the error when upgrading to Chrome 80 is slight different (and harder to fix), talked about in this issue here: https://github.com/borisbabic/browser_cookie3/issues/44

**Comment by brooksmcmillin** [comment]
I included a fix to this issue in my pull request as well 

https://github.com/borisbabic/browser_cookie3/pull/47

**Comment by borisbabic** [comment]
This should be fixed in >=0.10.1, thanks again for you contribution!
