### ISSUE TITLE
Module no longer functions with Firefox on Windows

### ISSUE THREAD

**Issue by Skylion007** [borisbabic/browser_cookie3#4]
Mozilla no longer stores profiles in the Program Files directory. They are now stored elsewhere.
%APPDATA%\Roaming\Mozilla\Firefox\Profiles\%some_random_string%.default
Now stores the default profile for Windows. The path should be updated to reflect this change.

**Comment by Skylion007** [comment]
Firefox 45.0.1 Windows 10 64bit

**Comment by borisbabic** [comment]
I've merged your pull request (thanks) and released a new version to pypi.
