### ISSUE TITLE
failed to find firefox cookie in firefox 72.0.1

### ISSUE THREAD

**Issue by anasofiapaixao** [borisbabic/browser_cookie3#40]
In Firefox 72.0.1 `profiles.ini` got propped up to the parent of Profiles, with relative paths being prepended by 'Profiles/', and the `profiles.ini` `Default=1` flag gets ignored when it contradicts the value of the `[Install<id>]` section, causing browser-cookie3 to be unable to find the cookie file.

**Comment by borisbabic** [comment]
Thanks again for your contributions, 0.10.0 has been released with #41
