### ISSUE TITLE
raise BrowserCookieError('Failed to find Chrome cookie')

### ISSUE THREAD

**Issue by Me-TheKing** [borisbabic/browser_cookie3#42]
hi 
I have this error (raise BrowserCookieError('Failed to find Chrome cookie')), and I use:
**windows 7 
browser_cookie3 0.10.0
python 3.7.4**
 
the code was:
```
import browser_cookie3
import requests

cookiejar = browser_cookie3.chrome()
resp = requests.get('https://www.google.com/', cookies=cookiejar)
print(resp.content)
```

but if I tried **browser_cookie3.firfox()** I have no error and it work just fine.
so I tried **Richard Penman browsercookie** and the code didn't give me any error but it didn't work.

thanks

**Comment by skyfire000** [comment]
you can put the direct cookies address in the argument:

cookiejar = browser_cookie3.chrome(cookie_file='C:\\Chrome\\User Data\\Default\\Cookies'')

**Comment by Me-TheKing** [comment]
thank skyfire000

I have my chrome cookies file in this path:
**C:\Users\user_name\AppData\Local\Google\Chrome\User Data\Profile 1**

see this answer in [stackoverflow](https://stackoverflow.com/a/42514256)

so i tried this answer :

```
import browser_cookie3
import requests
import os

chromecookies = os.path.join(os.path.expandvars("%userprofile%"),"AppData\\Local\\Google\\Chrome\\User Data\\Profile 1\\Cookies")
cookiejar = browser_cookie3.chrome(cookie_file=chromecookies)
resp = requests.get('https://www.google.com/', cookies=cookiejar)
print(resp.content)
```

but now I get this output about PermissionError:

> Traceback (most recent call last):
>   File "C:\Users\user\Desktop\python test\MAL project 1.0\cj.py", line 64, in <module>
>     cookiejar = browser_cookie3.chrome(cookie_file=chromecookiejarpath)
>   File "C:\Users\user\Anaconda3\lib\site-packages\browser_cookie3\__init__.py", line 350, in chrome
>     return Chrome(cookie_file, domain_name).load()
>   File "C:\Users\user\Anaconda3\lib\site-packages\browser_cookie3\__init__.py", line 176, in load
>     expires = expires.timestamp()
> OSError: [Errno 22] Invalid argument
> Exception ignored in: <function Chrome.__del__ at 0x0000000002D0F168>
> Traceback (most recent call last):
>   File "C:\Users\user\Anaconda3\lib\site-packages\browser_cookie3\__init__.py", line 148, in __del__
>     os.remove(self.tmp_cookie_file)
> PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\user\\AppData\\Local\\Temp\\tmp7ghienge.sqlite'
> [Finished in 2.1s]

as I say before I use:
**Windows 7 64-bit
browser_cookie3 0.10.0
python 3.7.4**
and **sublime Text**

**Comment by Me-TheKing** [comment]
I solved the problem by adding the **domain_name** with my cookies file.
the answer code is:

```
import browser_cookie3
import requests
import os

chromecookies = os.path.join(os.path.expandvars("%userprofile%"),"AppData\\Local\\Google\\Chrome\\User Data\\Profile 1\\Cookies")
cookiejar = browser_cookie3.chrome(cookie_file=chromecookies, domain_name="google.com")
resp = requests.get('https://www.google.com/', cookies=cookiejar)
print(resp.content)
```

**Comment by Sabrebar** [comment]
Any solution for this issue so far?

**Comment by robeadam** [comment]
make sure Chome is not running
