### ISSUE TITLE
KeyError: 'os_crypt'

### ISSUE THREAD

**Issue by zamsler98** [borisbabic/browser_cookie3#49]
Running Chrome Version 80.0.3987.106 and getting the following error
![image](https://user-images.githubusercontent.com/25695517/74752794-d85d6d80-5234-11ea-8b07-67b3cf9e5dde.png)

**Comment by brooksmcmillin** [comment]
What version of Windows are you running?

**Comment by brooketalcott** [comment]
The above 'quick-fix' worked for me and did not raise any additional errors
