### ISSUE TITLE
domain filter not working w/ Firefox

### ISSUE THREAD

**Issue by griswolf** [borisbabic/browser_cookie3#54]
`cj = browser_cookie3.firefox(domain_name=a_domain); len(cj) -> 62`

That seemed big, so I added this test

`len([x for x in cj if a_domain in x.domain]) -> 11`

I also checked for a domain of '' and found none

I looked at your code which appears reasonable, but clearly isn't doing what I expected. The scraping that I want to do works with either set of cookies, but I'm a bit OCD, so I have added a post-filter in my own code to send only the needed ones.

Firefox version: 75.0 (64-bit)
MacOS: version Catalina 10.15.4

**Comment by JCallicoat** [comment]
Looks like session cookies are always added without regard to domain.

**Comment by fawkesley** [comment]
Yep, I just accidentally uploaded my entire cookie file because of this :facepalm:
