### ISSUE TITLE
ValueError: invalid padding byte

### ISSUE THREAD

**Issue by leavesster** [borisbabic/browser_cookie3#6]
when I use in Mac OS
I just call 

> cj = browser_cookie3.chrome()

the system ask me the python to visit the keychain 
the it raise en error

>   Traceback (most recent call last):
>   File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydev_run_in_console.py", line 69, in <module>
>     globals = run_file(file, None, None)
>   File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydev_run_in_console.py", line 29, in run_file
>     pydev_imports.execfile(file, globals, locals)  # execute the script
>   File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
>     exec(compile(contents+"\n", file, 'exec'), glob, loc) 
>   File "/Users/xx/PycharmProjects/untitled1/login.py", line 12, in <module>
>     operate.xin()
> here is I use browse_cookies.chrome()
>   File "/Users/xx/PycharmProjects/untitled1/discuz.py", line 107, in xin
>     cookies = browser_cookie3.chrome()
>   File "/usr/local/lib/python3.5/site-packages/browser_cookie3/__init__.py", line 193, in chrome
>     return Chrome(cookie_file, domain_name).load()
>   File "/usr/local/lib/python3.5/site-packages/browser_cookie3/**init**.py", line 91, in load
>     value = self._decrypt(item[5], item[6])
>   File "/usr/local/lib/python3.5/site-packages/browser_cookie3/__init__.py", line 120, in _decrypt
>     decrypted += cipher.feed()
>   File "/usr/local/lib/python3.5/site-packages/pyaes/blockfeeder.py", line 169, in feed
>     result = self._final(self._buffer, self._padding)
>   File "/usr/local/lib/python3.5/site-packages/pyaes/blockfeeder.py", line 77, in _block_final_decrypt
>     return strip_PKCS7_padding(self.decrypt(data))
>   File "/usr/local/lib/python3.5/site-packages/pyaes/util.py", line 58, in strip_PKCS7_padding
>     raise ValueError("invalid padding byte")
> ValueError: invalid padding byte

**Comment by borisbabic** [comment]
What version are you using?

**Comment by alonkle1** [comment]
I used the latest version of chrome - 67.0.3396.99.
But I managed to fix the problem by moving to chrome 52.0.2743.116.

I looked in to the code and I saw a place where he asks for cookie v10, I had v11. This chrome version  is the latest version which still works with v10 encryption on the cookies so I moved to it.

I'm not satisfied with this solution but it works.

**Comment by borisbabic** [comment]
I'm sorry; I was unclear. What version of browser_cookie3 are you using?

**Comment by alonkle1** [comment]
version 0.6.4

**Comment by borisbabic** [comment]
I don't have issues, could you create a fresh cookie file and share it so I can test it? See https://github.com/borisbabic/browser_cookie3#fresh-cookie-files
