### ISSUE TITLE
Request: Save Cookies Back to Chrome

### ISSUE THREAD

**Issue by moneyblind** [borisbabic/browser_cookie3#65]
Hell all! Great update for the 80+. I recompiled myself before finding this one. However, I would like to ask if there is currently, or plans to be, a way to inject cookies directly into the file via this library.

I am working on automation with the server changing the cookie after every action. After the automation is done, i would like to take the most recent cookie and save it back to the file so when i go back to my chrome browser, it has the newest cookie.

Its late here, so if you could already do that, sorry, help a brother out!

**Comment by borisbabic** [comment]
No plans for this
