### ISSUE TITLE
from pysqlite2 import dbapi2 as sqlite3 or ModuleNotFoundError No module named 'pysqlite2'

### ISSUE THREAD

**Issue by githublyff** [borisbabic/browser_cookie3#74]
win7，32-bit， anaconda env-py3.7 prompt：
1、ModuleNotFoundError: No module named 'pysqlite2'
2、from _sqlite3 import *
ImportError: DLL load failed: The specified module could not be found

resolvent：
Go to the official website of SQLite3（ https://www.sqlite.org/download.html ）Download the corresponding plug-ins according to your own system and bits (32-bit or 64 bit). After downloading, unzip and copy the two files (SQLite3. Def and SQLite3. DLL) to the DLLs directory of Anaconda or the DLLs directory of your own virtual environment.

**Comment by renjx** [comment]
it's done! thank you
