### ISSUE TITLE
Doesn't work with latest Chrome version

### ISSUE THREAD

**Issue by Gistix** [borisbabic/browser_cookie3#81]
I'm on windows 10 20H2 running Chrome version 90.0.4430.85, it worked fine while I was in 89.0.4389.128.

`Traceback (most recent call last):
  File "C:\Users\Gistix\AppData\Local\Programs\Python\Python37\lib\site-packages\browser_cookie3\__init__.py", line 267, in load
    cur.execute('SELECT host_key, path, secure, expires_utc, name, value, encrypted_value '
sqlite3.OperationalError: no such column: secure`

**Comment by alzamer2** [comment]
what your code version?
version 0.12.1 was released recently to fix this error
if you have no idea to to upgrade your module type this in administrator privileges CMD
`pip3 install -U browser_cookie3`

**Comment by mhavrlent** [comment]
@alzamer2 
For me it works after the upgrade to version 0.12.1.

**Comment by Gistix** [comment]
Working fine after I upgraded to version 0.12.1.
