### ISSUE TITLE
error when load cookies

### ISSUE THREAD

**Issue by evenuss** [borisbabic/browser_cookie3#82]
import browser_cookie3
cj = browser_cookie3.chrome()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Work\btpn\env\lib\site-packages\browser_cookie3\__init__.py", line 592, in chrome
    return Chrome(cookie_file, domain_name, key_file).load()
  File "E:\Work\btpn\env\lib\site-packages\browser_cookie3\__init__.py", line 382, in __init__
    super().__init__(browser='Chrome', cookie_file=cookie_file, domain_name=domain_name, key_file=key_file, **args)
  File "E:\Work\btpn\env\lib\site-packages\browser_cookie3\__init__.py", line 190, in __init__
    self.__add_key_and_cookie_file(**kwargs)
  File "E:\Work\btpn\env\lib\site-packages\browser_cookie3\__init__.py", line 248, in __add_key_and_cookie_file
    raise BrowserCookieError('Failed to find {} cookie'.format(self.browser))
browser_cookie3.BrowserCookieError: Failed to find Chrome cookie
>>> cj = browser_cookie3.load()
Traceback (most recent call last):
  File "E:\Work\btpn\env\lib\site-packages\browser_cookie3\__init__.py", line 268, in load
    'FROM cookies WHERE host_key like "%{}%";'.format(self.domain_name))
sqlite3.OperationalError: no such column: secure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Work\btpn\env\lib\site-packages\browser_cookie3\__init__.py", line 626, in load
    for cookie in cookie_fn(domain_name=domain_name):
  File "E:\Work\btpn\env\lib\site-packages\browser_cookie3\__init__.py", line 610, in edge
    return Edge(cookie_file, domain_name, key_file).load()
  File "E:\Work\btpn\env\lib\site-packages\browser_cookie3\__init__.py", line 272, in load
    'FROM cookies WHERE host_key like "%{}%";'.format(self.domain_name))
sqlite3.OperationalError: Could not decode to UTF-8 column 'encrypted_value' with text 'v10tb}obyM�(☻������L>��=����0e5���x�→▬s�♀Y;�Rfe�����4�u�'c��?�^z�+�▲-F�:��y�(��♣�►���Z��g����#=�↔�☻FP=lD�|A'`

**Comment by borisbabic** [comment]
What version are you using?

**Comment by evenuss** [comment]
> What version are you using?

i'm using browser-cookie3    0.12.0

**Comment by venantiusgalih** [comment]
I have the same error too, when i just want to get the cookies in the browser.

> @app.route("/test1", methods=["GET"])
> 
> def test1():
>     cj = browser_cookie3.load()
>     for c in cj:
>         print(c.domain, c.name, c.value)
>     return "OK"

The error was:

> 127.0.0.1 - - [29/Apr/2021 10:49:50] "GET /test1 HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "C:\Users\venan\.conda\envs\test-flask\Lib\site-packages\browser_cookie3\__init__.py", line 267, in load
>     cur.execute('SELECT host_key, path, secure, expires_utc, name, value, encrypted_value '
> sqlite3.OperationalError: no such column: secure
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\venan\.conda\envs\test-flask\Lib\site-packages\flask\app.py", line 2464, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "C:\Users\venan\.conda\envs\test-flask\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
>     response = self.handle_exception(e)
>   File "C:\Users\venan\.conda\envs\test-flask\Lib\site-packages\flask\app.py", line 1867, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\venan\.conda\envs\test-flask\Lib\site-packages\flask\_compat.py", line 39, in reraise
>     raise value
>   File "C:\Users\venan\.conda\envs\test-flask\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
>     response = self.full_dispatch_request()
>   File "C:\Users\venan\.conda\envs\test-flask\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "C:\Users\venan\.conda\envs\test-flask\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "C:\Users\venan\.conda\envs\test-flask\Lib\site-packages\flask\_compat.py", line 39, in reraise
>     raise value
>   File "C:\Users\venan\.conda\envs\test-flask\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\Users\venan\.conda\envs\test-flask\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "D:\WORK OLD\BTPN - Social Media Listening\Development\test-twitter-binding\app\views.py", line 86, in test1
>     cj = browser_cookie3.load()
>   File "C:\Users\venan\.conda\envs\test-flask\Lib\site-packages\browser_cookie3\__init__.py", line 626, in load
>     for cookie in cookie_fn(domain_name=domain_name):
>   File "C:\Users\venan\.conda\envs\test-flask\Lib\site-packages\browser_cookie3\__init__.py", line 592, in chrome
>     return Chrome(cookie_file, domain_name, key_file).load()
>   File "C:\Users\venan\.conda\envs\test-flask\Lib\site-packages\browser_cookie3\__init__.py", line 271, in load
>     cur.execute('SELECT host_key, path, is_secure, expires_utc, name, value, encrypted_value '
> sqlite3.OperationalError: Could not decode to UTF-8 column 'encrypted_value' with text 'v10�������♦♫^D�8�Opk�                                                                                                                   �Q�������>6z�]���_���SD�����[����#��Rc▬��'

**Comment by rafiibrahim8** [comment]
@evenuss Upgrade browser-cookie3 to the latest version (0.12.1). This problem has been fixed in the latest version.
