### ISSUE TITLE
File encoding error when calling browser_cookie3.load()

### ISSUE THREAD

**Issue by masterisk** [borisbabic/browser_cookie3#85]
```
  File "C:\Python39\lib\site-packages\browser_cookie3\__init__.py", line 502, in load
    for cookie in cookie_fn(domain_name=domain_name):
  File "C:\Python39\lib\site-packages\browser_cookie3\__init__.py", line 492, in firefox
    return Firefox(cookie_file, domain_name).load()
  File "C:\Python39\lib\site-packages\browser_cookie3\__init__.py", line 347, in __init__
    cookie_file = cookie_file or self.find_cookie_file()
  File "C:\Python39\lib\site-packages\browser_cookie3\__init__.py", line 414, in find_cookie_file
    cookie_files = glob.glob(os.path.join(Firefox.get_default_profile(user_data_path), 'cookies.sqlite')) \
  File "C:\Python39\lib\site-packages\browser_cookie3\__init__.py", line 376, in get_default_profile
    config.read(profiles_ini_path)
  File "C:\Python39\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "C:\Python39\lib\configparser.py", line 1082, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'C:\\Users\\Masterisk\\AppData\\Roaming\\Mozilla\\Firefox\\profiles.ini', line: 1
'ÿþ[\x00G\x00e\x00n\x00e\x00r\x00a\x00l\x00]\x00\n'
```

This is occurring because the Firefox profiles.ini is encoded in utf-16. -- I'm unsure if this is a recent change or an error of some sort.

Line 492 in browser_cookie3\\\_\_init\_\_.py calls "config.read(profiles_ini_path)"
config.read has an optional argument for encoding
if you use "config.read(profiles_ini_path, encoding='utf-16')" this works.

For my own use I've changed line 492 to be as follows:
```
try:
    config.read(profiles_ini_path)
except configparser.MissingSectionHeaderError:
    config.read(profiles_ini_path, encoding='utf-16')
```
There is probably a better way to fix this with detecting the file encoding with the chardet module.
But this should be a step in the right direction if this isn't just a weird issue with my environment.

**Comment by borisbabic** [comment]
What browser/library version are you using?

**Comment by masterisk** [comment]
> 
> 
> What browser/library version are you using?

Firefox 88.0.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0)
browser-cookie3 0.12.1

**Comment by netchose** [comment]
Hi,
Same problem for me  on Windows 10 and Firefox 89 browser-cookie3 0.12.1
the masterisk 's patch do the trick
