### ISSUE TITLE
Not working with Edge

### ISSUE THREAD

**Issue by ybshin5657** [borisbabic/browser_cookie3#93]
browser_cookie3 is returning empty CookieJar from Edge browser. (works just fine with Chrome.)
I have tried both 'browser_cookie3.egde' and 'browser_cookie3.load' but no luck, even with admin privilege.
Edge verision is 92.0.902.55

**Comment by borisbabic** [comment]
Are you sure your cookies file is in the default location?

**Comment by techthoughts2** [comment]
Modern versions of Edge now contain only a ```deprecated.cookie``` file which contains the following entry:

```
Cookies are no longer stored in files.  Please use Internet*Cookie* APIs to access cookies.
```
