### ISSUE TITLE
Failed to build cryptography error - termux

### ISSUE THREAD

**Issue by ghost** [borisbabic/browser_cookie3#98]
Could not build wheels for cryptography. which is required to install pyproject.toml-based projects

**Comment by pavan3999** [comment]
export CARGO_BUILD_TARGET=aarch64-linux-android next try pip install cryptography. Btw is browser_cookie3 supports in termux android?

**Comment by 13Quavo** [comment]
Hi I have this issue, I tried installing Cryptography but this error appears https://pastebin.com/1WqCyRhz

**Comment by rafiibrahim8** [comment]
Hi,
`browser-cookie3` doesn't support android. And as of version `0.17.0` it doesn't depend on cryptography. So you can give it another go now. 
Thanks :purple_heart:
